apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: skylearn

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: ghcr.io/adithyansk-2002/skylearn-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 15
            periodSeconds: 10

          volumeMounts:
            - name: backend-storage
              mountPath: /data

      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-pvc
