---
- name: Configure SkyLearn Infrastructure
  hosts: webservers
  become: true

  roles:
    - packages
    - users
    - directories
    - scripts
    - permissions
    - hostname
    - nginx
    - firewall
