name: SkyLearn CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository Structure
        run: |
          test -f README.md
          test -f LICENSE

          test -d ansible
          test -d app
          test -d assets
          test -d aws
          test -d cicd
          test -d docker
          test -d docs
          test -d kubernetes
          test -d monitoring
          test -d scripts
          test -d terraform

      - name: Verify Ansible Structure
        run: |
          test -f ansible/ansible.cfg
          test -f ansible/inventories/hosts.ini
          test -d ansible/inventories/group_vars
          test -d ansible/inventories/host_vars
          test -d ansible/playbooks
          test -d ansible/roles
          test -f ansible/playbooks/site.yml

      - name: Install Ansible and yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible yamllint

      - name: Ansible Syntax Check
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventories/hosts.ini \
            playbooks/site.yml \
            --syntax-check

      - name: Lint YAML Files
        run: yamllint -c .yamllint .

      - name: Verify Shell Scripts
        run: |
          find . -type f -name "*.sh" -exec test -x {} \;

      - name: Show Git Information
        run: |
          git status
          git log --oneline -5

      - name: CI Passed
        run: |
          echo "======================================="
          echo " SkyLearn Repository Validation Passed "
          echo "======================================="


  docker-build:
    name: Build Docker Images
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        run: docker build -t skylearn-backend ./app/backend

      - name: Build Frontend Image
        run: docker build -f app/frontend/Dockerfile -t skylearn-frontend .

      - name: Validate Docker Compose
        working-directory: docker/compose
        run: docker compose config

      - name: Docker Build Passed
        run: |
          echo "======================================="
          echo " SkyLearn Docker Build Passed "
          echo "======================================="

  deploy:
    name: Deploy to EC2
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/devopsadmin/SkyLearn-DevOps

            git pull origin main

            cd docker/compose

            docker compose up --build -d

            echo "Waiting for application..."

            sleep 10

            curl -f http://localhost/api/health
