name: Rollback SkyLearn

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image tag (Commit SHA)"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "Rollback requested for version: ${{ github.event.inputs.version }}"
