name: Rollback SkyLearn

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image tag (Commit SHA)"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/devopsadmin/SkyLearn-DevOps/docker/compose

            export IMAGE_TAG=${{ github.event.inputs.image_tag }}

            echo "Rolling back to image tag: $IMAGE_TAG"

            docker compose pull

            docker compose up -d

            echo "Waiting for application..."

            sleep 10

            curl -f http://localhost/api/health
